services:
  mysql:
    image: mysql:9.7@sha256:e370cd5f64599d46985b7729b452f2153825246f88d82753ec595c5dfc6fef6a
    environment:
      - MYSQL_ROOT_PASSWORD=alloy
      - MYSQL_DATABASE=alloy
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-palloy"]
      interval: 10s
      timeout: 5s
      retries: 5
