services:
  mysql:
    image: mysql:9.7@sha256:ae269281abffe401d65f04cb54d45a069a495b8174b9c0a815e502fed7fa0370
    environment:
      - MYSQL_ROOT_PASSWORD=alloy
      - MYSQL_DATABASE=alloy
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-palloy"]
      interval: 10s
      timeout: 5s
      retries: 5
