services:
  mysql:
    image: mysql:9.7@sha256:c9e48b0c008f1936d4139d1c0dcd5950a9dbe57d4d40f383013cde432fa6d6aa
    environment:
      - MYSQL_ROOT_PASSWORD=alloy
      - MYSQL_DATABASE=alloy
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-palloy"]
      interval: 10s
      timeout: 5s
      retries: 5
