---
cluster:
  name: meta-monitoring-tutorial

destinations:
  tempo:
    type: otlp
    url: http://tempo.meta.svc.cluster.local:4317
    metrics:
      enabled: false
    logs:
      enabled: false
    traces:
      enabled: true

applicationObservability:
  enabled: true
  collector: alloy-receiver
  receivers:
    otlp:
      grpc:
        enabled: true
      http:
        enabled: true
  metrics:
    enabled: false
  logs:
    enabled: false

collectors:
  alloy-receiver:
    presets: [deployment]
