---
cluster:
  name: meta-monitoring-tutorial

destinations:
  prometheus:
    type: prometheus
    url: http://prometheus-server.meta.svc.cluster.local:80/api/v1/write

clusterMetrics:
  enabled: true

annotationAutodiscovery:
  enabled: true
  collector: alloy-metrics

collectors:
  alloy-metrics:
    presets: [clustered, statefulset]

telemetryServices:
  kube-state-metrics:
    deploy: true
