services:
  demo-app:
    image: golang:1.26@sha256:b54cbf583d390341599d7bcbc062425c081105cc5ef6d170ced98ef9d047c716
    ports:
      - 6060:6060
    volumes:
      - ./app:/app
    working_dir: /app
    command: go run main.go
