services:
  demo-app:
    image: golang:1.26@sha256:d184d9be4c13614e28498d632eeaaac704d662f18ad357e1df74a44424236cea
    ports:
      - 6060:6060
    volumes:
      - ./app:/app
    working_dir: /app
    command: go run main.go
