services:
  minio:
    image: "minio/minio:RELEASE.2024-10-29T16-01-48Z@sha256:ebd2af76d40ff25ccc630533615f7ccd55fbe83d629a4b7c7a1b6311c1af3d6c"
    restart: "unless-stopped"
    entrypoint:
      - "sh"
      - "-euc"
      - "mkdir -p /data/loki && /usr/bin/docker-entrypoint.sh minio server --quiet --address 0.0.0.0:9000 --console-address ':9001' /data"
    volumes:
      - "./.customData/minio:/data"
    environment:
      - "MINIO_ROOT_USER=myuser"
      - "MINIO_ROOT_PASSWORD=mypass"
    ports:
      - "9000:9000"
      - "9001:9001"

  loki:
    image: "grafana/loki:latest@sha256:87f0a067673756a3cede1bcbf0c74875f7df9b09fddb53e399d0c576f756cfcc"
    restart: "unless-stopped"
    command: "-config.file=/etc/loki/server.yml"
    volumes:
      - "./support/loki/server.yml:/etc/loki/server.yml"
    ports:
      - "3100:3100"
      - "7946"
    depends_on:
      - "minio"

  grafana:
    image: "grafana/grafana:latest@sha256:121a7a9ece6dc10b969f1f96eed64b4f07dfac0d0b8abc070f7cb83bbde86f63"
    restart: "unless-stopped"
    user: '0'
    volumes:
      - "./support/grafana/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml"
      - "./.customData/grafana:/var/lib/grafana"
    ports:
      - "3000:3000"
    depends_on:
      - "loki"
      
  alloy:
    image: "grafana/alloy:latest@sha256:4f6ddc56ffdcf8a6316748fc5162972e20cb301523cac1bb4a31957df733ae9b"
    restart: "unless-stopped"
    command: "run --server.http.listen-addr=0.0.0.0:3000 --storage.path=/var/lib/alloy/data /etc/alloy/config.alloy"
    volumes:
      - "./config.alloy:/etc/alloy/config.alloy"
    ports:
      - "3005:3000"
      - "3015:3005"
    depends_on:
      - "loki"

###Local app that generates logs
  promtail:
    image: "grafana/promtail:latest@sha256:6cfa64ec432b24a912d640e2edb940eeae2666f61861a66c121d763dd7241381"
    volumes:
      - "./support/promtail/promtail-config.yml:/etc/promtail/config.yml"
      - "./support/promtail/myCustomLog.txt:/var/log/myCustomLog.txt"
    ports:
      - "9080:9080"
    depends_on: 
      - "alloy"