services:
  minio:
    image: "minio/minio:RELEASE.2024-10-29T16-01-48Z@sha256:ebd2af76d40ff25ccc630533615f7ccd55fbe83d629a4b7c7a1b6311c1af3d6c"
    restart: "unless-stopped"
    entrypoint:
      - "sh"
      - "-euc"
      - "mkdir -p /data/loki && /usr/bin/docker-entrypoint.sh minio server --quiet --address 0.0.0.0:9000 --console-address ':9001' /data"
    volumes:
      - "./.customData/minio:/data"
    environment:
      - "MINIO_ROOT_USER=myuser"
      - "MINIO_ROOT_PASSWORD=mypass"
    ports:
      - "9000:9000"
      - "9001:9001"

  loki:
    image: "grafana/loki:latest@sha256:73e905b51a7f917f7a1075e4be68759df30226e03dcb3cd2213b989cc0dc8eb4"
    restart: "unless-stopped"
    command: "-config.file=/etc/loki/server.yml"
    volumes:
      - "./support/loki/server.yml:/etc/loki/server.yml"
    ports:
      - "3100:3100"
      - "7946"
    depends_on:
      - "minio"

  grafana:
    image: "grafana/grafana:latest@sha256:0f86bada30d65ef9d0183b90c1e2682ac92d53d95da8bed322b984ea78a4a73a"
    restart: "unless-stopped"
    user: '0'
    volumes:
      - "./support/grafana/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml"
      - "./.customData/grafana:/var/lib/grafana"
    ports:
      - "3000:3000"
    depends_on:
      - "loki"
      
  alloy:
    image: "grafana/alloy:latest@sha256:6e00cf7c5a692ff5f24844529416ed017d76fce922f8199004e73d5eca46b6b8"
    restart: "unless-stopped"
    command: "run --server.http.listen-addr=0.0.0.0:3000 --storage.path=/var/lib/alloy/data /etc/alloy/config.alloy"
    volumes:
      - "./config.alloy:/etc/alloy/config.alloy"
    ports:
      - "3005:3000"
      - "3015:3005"
    depends_on:
      - "loki"

###Local app that generates logs
  promtail:
    image: "grafana/promtail:latest@sha256:6cfa64ec432b24a912d640e2edb940eeae2666f61861a66c121d763dd7241381"
    volumes:
      - "./support/promtail/promtail-config.yml:/etc/promtail/config.yml"
      - "./support/promtail/myCustomLog.txt:/var/log/myCustomLog.txt"
    ports:
      - "9080:9080"
    depends_on: 
      - "alloy"