services:
  minio:
    image: "minio/minio:RELEASE.2024-10-29T16-01-48Z@sha256:ebd2af76d40ff25ccc630533615f7ccd55fbe83d629a4b7c7a1b6311c1af3d6c"
    restart: "unless-stopped"
    entrypoint:
      - "sh"
      - "-euc"
      - "mkdir -p /data/loki && /usr/bin/docker-entrypoint.sh minio server --quiet --address 0.0.0.0:9000 --console-address ':9001' /data"
    volumes:
      - "./.customData/minio:/data"
    environment:
      - "MINIO_ROOT_USER=myuser"
      - "MINIO_ROOT_PASSWORD=mypass"
    ports:
      - "9000:9000"
      - "9001:9001"

  loki:
    image: "grafana/loki:latest@sha256:be31579ac047e9f78b81e48f3b69d3af709e7299b431d5aa78bcda43382f9511"
    restart: "unless-stopped"
    command: "-config.file=/etc/loki/server.yml"
    volumes:
      - "./support/loki/server.yml:/etc/loki/server.yml"
    ports:
      - "3100:3100"
      - "7946"
    depends_on:
      - "minio"

  grafana:
    image: "grafana/grafana:latest@sha256:ba93c9d192e58b23e064c7f501d453426ccf4a85065bf25b705ab1e98602bfb1"
    restart: "unless-stopped"
    user: '0'
    volumes:
      - "./support/grafana/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml"
      - "./.customData/grafana:/var/lib/grafana"
    ports:
      - "3000:3000"
    depends_on:
      - "loki"
      
  alloy:
    image: "grafana/alloy:latest@sha256:f94b1c82957accb77cd11385fd5e3600758ef1b1ab79557c97319ad28590735a"
    restart: "unless-stopped"
    command: "run --server.http.listen-addr=0.0.0.0:3000 --storage.path=/var/lib/alloy/data /etc/alloy/config.alloy"
    volumes:
      - "./config.alloy:/etc/alloy/config.alloy"
    ports:
      - "3005:3000"
      - "3015:3005"
    depends_on:
      - "loki"

###Local app that generates logs
  promtail:
    image: "grafana/promtail:latest@sha256:ba2f727003e28541bf8a9b9ff92a8adbe5a48f1cfe388493f9266bbd94891fe3"
    volumes:
      - "./support/promtail/promtail-config.yml:/etc/promtail/config.yml"
      - "./support/promtail/myCustomLog.txt:/var/log/myCustomLog.txt"
    ports:
      - "9080:9080"
    depends_on: 
      - "alloy"