services:
  stress-cpu:
    image: golang:1.26@sha256:ae5a2316d12f3e78fd99177dad452e6ad4f240af2d71d57b480c3477f250fec6
    container_name: stress-cpu
    volumes:
      - ./app:/app
    working_dir: /app
    command: go run . cpu
    restart: unless-stopped

  stress-mem:
    image: golang:1.26@sha256:ae5a2316d12f3e78fd99177dad452e6ad4f240af2d71d57b480c3477f250fec6
    container_name: stress-mem
    volumes:
      - ./app:/app
    working_dir: /app
    command: go run . mem
    restart: unless-stopped
