---
cluster:
  name: meta-monitoring-tutorial

destinations:
  pyroscope:
    type: pyroscope
    url: http://pyroscope.meta.svc.cluster.local:4040

profiling:
  enabled: true
  collector: alloy-profiles
  pprof:
    enabled: true

collectors:
  alloy-profiles:
    presets: [privileged, daemonset]
