services:
  postgres:
    image: postgres:18@sha256:4aabea78cf39b90e834caf3af7d602a18565f6fe2508705c8d01aa63245c2e20
    environment:
      POSTGRES_USER: alloy
      POSTGRES_PASSWORD: alloy
      POSTGRES_DB: alloy
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U alloy"]
      interval: 5s
      timeout: 5s
      retries: 5
